In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("insurance.csv")
dataset

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
data=dataset[["age","bmi","charges"]]

In [4]:
data["bmi"]=data["bmi"].astype(int)
data["charges"]=data["charges"].astype(int)

<ipython-input-4-20cf8a735f22>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["bmi"]=data["bmi"].astype(int)
<ipython-input-4-20cf8a735f22>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["charges"]=data["charges"].astype(int)


In [5]:
data.dtypes

age        int64
bmi        int64
charges    int64
dtype: object

In [6]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

## Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y, test_size=0.20, random_state=0)

## Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

## Training the K-NN model on the Training set

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)

classifier.fit(x_train, y_train)

KNeighborsClassifier()

## Predicting a new result

In [10]:
classifier.predict(sc.transform([[28,33]]))

array([3171])

## Predicting the Test set results

In [11]:
y_pred=classifier.predict(x_test)

In [18]:
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)

array([[ 9377,  9724],
       [ 7789,  8547],
       [ 7804, 45702],
       [12648, 12950],
       [ 7526,  9644],
       [ 4134,  4500],
       [ 1615,  2198],
       [ 8457, 11436],
       [ 4646,  7537],
       [ 3659,  5425],
       [ 3260,  6753],
       [ 8442, 10493],
       [ 6849,  7337],
       [ 5125,  4185],
       [ 3213, 18310],
       [ 8703, 10702],
       [12142, 12523],
       [ 2497,  3490],
       [ 5028,  6457],
       [ 1639, 33475],
       [ 9863, 23967],
       [10976, 12643],
       [ 9377, 23045],
       [ 8026, 23065],
       [ 1391,  1674],
       [ 4673,  4667],
       [ 2680,  3732],
       [ 5699,  7682],
       [ 3353,  3756],
       [ 8520,  8413],
       [ 5974,  8059],
       [10982, 48970],
       [12981, 12979],
       [10226, 20630],
       [ 2302, 14571],
       [ 2866,  4137],
       [ 7152,  8347],
       [ 3277, 51194],
       [ 6571, 40003],
       [ 1391,  1880],
       [ 5855,  5458],
       [ 2866,  2867],
       [ 5415, 20149],
       [113

## Making the Confusion Matrix


In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
accuracy_score(y_test,y_pred)

0.0037313432835820895